/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    DashboardFooter: typeof import('./src/components/DashboardFooter.vue')['default']
    DashboardHeader: typeof import('./src/components/DashboardHeader.vue')['default']
    DashboardSidebar: typeof import('./src/components/DashboardSidebar.vue')['default']
    HeaderBtn: typeof import('./src/components/HeaderBtn.vue')['default']
    HomeHeader: typeof import('./src/components/HomeHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarDrawer: typeof import('./src/components/SidebarDrawer.vue')['default']
    SidebarList: typeof import('./src/components/SidebarList.vue')['default']
  }
}
